### ISSUE TITLE
新功能

### ISSUE THREAD

**Issue by gujiniCY** [mars05/crud-intellij-plugin#1]
首先非常感谢作者可以贡献这么好的项目，其次可以考虑支持mybatis-plus的生成吗？自动生成Service extends IService<T>，Mapper extends BaseMapper<T>,实体类@TableName()，@TableId@TableField等等这些

**Comment by imyzt** [comment]
@gujiniCY 可以关注一下这个 [https://github.com/imyzt/crud-intellij-plugin](https://github.com/imyzt/crud-intellij-plugin)，我最近在加，可以一起协助开发

**Comment by imyzt** [comment]
@gujiniCY 目前Mybatis-Plus创建项目基本没有问题了。右键生成还没时间调

**Comment by mars05** [comment]
@imyzt 您好，感谢您对插件做的一些功能添加和细节调整，如果可以的话，希望可以提个PR合并过来。

**Comment by imyzt** [comment]
@mars05 我对您的插件做了较大的调整，如果直接提交PR可能会造成较大的文件冲突产生。最近在着手生成Dockerfile文件等内容，待我调整完毕提交一个PR。
