### ISSUE TITLE
local.properties (系统找不到指定的文件。)

### ISSUE THREAD

**Issue by masteryourself** [mars05/crud-intellij-plugin#2]
![image](https://user-images.githubusercontent.com/31031735/67190537-b7ba0e00-f422-11e9-925a-3d187745fe62.png)

what's that?

**Comment by mars05** [comment]
这个是用于发布插件需要的，所以没有提交，你可以暂时手动创建一个，或者把.build文件里加载local.properties的地方和TOKEN注释掉

**Comment by masteryourself** [comment]
好的 没用过gradle 感谢
