### ISSUE TITLE
你好，我在本地的main方法可以正常连接数据库，打成jar包安装成插件，就找不到数据库驱动？

### ISSUE THREAD

**Issue by pengfeizan** [mars05/crud-intellij-plugin#3]

**Comment by mars05** [comment]
你好，手动安装插件需要使用zip包 （crud-intellij-plugin\build\distributions\crud-plugin-1.0.3.zip）

**Comment by pengfeizan** [comment]
谢谢，已解决



---原始邮件---
发件人: "Xiao Yu"<notifications@github.com&gt;
发送时间: 2020年6月11日(周四) 中午11:42
收件人: "mars05/crud-intellij-plugin"<crud-intellij-plugin@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"pengfeizan"<737601296@qq.com&gt;;
主题: Re: [mars05/crud-intellij-plugin] 你好，我在本地的main方法可以正常连接数据库，打成jar包安装成插件，就找不到数据库驱动？ (#3)




 
你好，手动安装插件需要使用zip包 （crud-intellij-plugin\build\distributions\crud-plugin-1.0.3.zip）
