### ISSUE TITLE
VARCHAR2 / NVARCHAR2 support for OracleDB / JPA

### ISSUE THREAD

**Issue by teamolhuang** [mars05/crud-intellij-plugin#5]
hi, we're using Spring JPA + OracleDB here and we use VARCHAR2 or NVARCHAR2 to store strings.
it should be mapped into `String`, but the plugin is currently converting them into `Object` which cause program to fail.

Hope this can get fixed soon. Or I wonder if users can fix the convertion rules by themselves? This is a really wonderful project and I hope maybe in someway I can contribute too.

**Comment by mars05** [comment]
@teamolhuang 感谢反馈，插件最新版本已将该问题修复
